#!/usr/bin/env python3
"""Validate the eight static blog pages and their homepage catalogue metadata."""
from __future__ import annotations

import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

from bs4 import BeautifulSoup
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BLOG = ROOT / "public" / "blog"
CONTENT = ROOT / "content" / "blog"
BASE = "https://aivisionconsulting.co.uk"
EXPECTED = {
    "what-is-ai",
    "8-ai-prompts-every-job-seeker-needs-right-now",
    "ai-chatbot-for-your-website",
    "ai-training-for-employees",
    "how-to-start-an-ai-side-hustle",
    "use-ai-civil-service-application",
    "what-to-automate-first-small-business",
    "whatsapp-lead-automation-small-business",
}
ERRORS: list[str] = []
WARNINGS: list[str] = []


def fail(slug: str, message: str) -> None:
    ERRORS.append(f"{slug}: {message}")


def meta(soup: BeautifulSoup, *, name: str | None = None, prop: str | None = None) -> str:
    tag = soup.find("meta", attrs={"name": name}) if name else soup.find("meta", attrs={"property": prop})
    return str(tag.get("content", "")).strip() if tag else ""


def parse_catalogue() -> dict[str, dict[str, str]]:
    text = (ROOT / "src" / "data" / "blog.ts").read_text(encoding="utf-8")
    cards: dict[str, dict[str, str]] = {}
    for block in re.findall(r"\{\n(.*?)\n  \},", text, flags=re.S):
        values = {
            key: value
            for key, _quote, value in re.findall(r"^\s+(\w+):\s*(['\"])(.*?)\2,?$", block, flags=re.M)
        }
        if "slug" in values:
            cards[values["slug"]] = values
    return cards


def visible_faqs(soup: BeautifulSoup) -> list[tuple[str, str]]:
    def clean_text(tag) -> str:
        copy = BeautifulSoup(str(tag), "html.parser")
        for hidden in copy.select(".sr-only"):
            hidden.decompose()
        return copy.get_text(" ", strip=True)

    result = []
    items = soup.select(".faq-item")
    if items:
        for item in items:
            q = item.find("h3")
            a = item.find("p")
            if q and a:
                result.append((clean_text(q), clean_text(a)))
        return result
    section = soup.select_one('[aria-label="Frequently asked questions"]')
    if section:
        for q in section.find_all("h3", recursive=False):
            a = q.find_next_sibling("p")
            if a:
                result.append((clean_text(q), clean_text(a)))
    return result


def main() -> int:
    styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
    responsive_image_rule = re.search(r"img\s*\{[^}]*\bheight:\s*auto\s*;?[^}]*\}", styles, flags=re.S)
    if not responsive_image_rule:
        fail("styles", "base image rule must set height: auto so width/height attributes preserve their aspect ratio")

    pages = {p.stem: p for p in BLOG.glob("*.html")}
    if set(pages) != EXPECTED:
        fail("catalogue", f"static pages are {sorted(pages)}, expected {sorted(EXPECTED)}")
    cards = parse_catalogue()
    if set(cards) != EXPECTED:
        fail("catalogue", f"blog.ts slugs are {sorted(cards)}, expected {sorted(EXPECTED)}")
    generated_slugs = {path.stem for path in CONTENT.glob("*.md")}

    today = date.today().isoformat()
    all_internal_links: set[str] = set()
    for slug in sorted(EXPECTED & pages.keys()):
        path = pages[slug]
        html = path.read_text(encoding="utf-8")
        soup = BeautifulSoup(html, "html.parser")
        card = cards.get(slug, {})
        if slug in generated_slugs and "<!-- Generated by scripts/generate-static-blog.py -->" not in html:
            fail(slug, "generated-file ownership marker missing")
        json_nodes = []
        canonical = f"{BASE}/blog/{slug}"

        title = soup.title.get_text(strip=True) if soup.title else ""
        h1s = soup.find_all("h1")
        h1 = h1s[0].get_text(" ", strip=True) if len(h1s) == 1 else ""
        description = meta(soup, name="description")
        canonical_tag = soup.find("link", rel="canonical")
        canonical_value = str(canonical_tag.get("href", "")) if canonical_tag else ""
        og_title, og_desc = meta(soup, prop="og:title"), meta(soup, prop="og:description")
        og_url, og_image = meta(soup, prop="og:url"), meta(soup, prop="og:image")
        og_image_alt = meta(soup, prop="og:image:alt")
        og_image_width = meta(soup, prop="og:image:width")
        og_image_height = meta(soup, prop="og:image:height")
        og_image_type = meta(soup, prop="og:image:type")
        article_author = meta(soup, prop="article:author")
        twitter_title = meta(soup, name="twitter:title")
        twitter_desc = meta(soup, name="twitter:description")
        twitter_image = meta(soup, name="twitter:image")
        twitter_image_alt = meta(soup, name="twitter:image:alt")

        if not 30 <= len(title) <= 65: fail(slug, f"title length {len(title)} is outside 30–65")
        if not 120 <= len(description) <= 165: fail(slug, f"description length {len(description)} is outside 120–165")
        if len(h1s) != 1: fail(slug, f"expected one H1, found {len(h1s)}")
        if canonical_value != canonical: fail(slug, f"canonical is {canonical_value!r}")
        if og_url != canonical: fail(slug, f"og:url is {og_url!r}")
        if not (title == og_title == twitter_title == card.get("metaTitle")): fail(slug, "title, OG, Twitter and blog.ts metaTitle differ")
        if not (description == og_desc == twitter_desc == card.get("metaDescription")): fail(slug, "descriptions differ across metadata")
        if og_image != twitter_image or og_image != card.get("image"): fail(slug, "image URL differs across metadata and blog.ts")
        if og_image_alt != card.get("imageAlt") or twitter_image_alt != card.get("imageAlt"): fail(slug, "social image alt text differs from blog.ts")
        if (og_image_width, og_image_height, og_image_type) != ("1600", "900", "image/png"): fail(slug, "social image dimensions or MIME type are wrong")
        if article_author != f"{BASE}/about-eric-nwankwo/": fail(slug, "article:author is not the canonical profile URL")
        expected_image = f"{BASE}/images/blog/{slug}.png"
        if og_image != expected_image: fail(slug, f"image URL is {og_image!r}")
        image_path = ROOT / "public" / urlparse(og_image).path.lstrip("/")
        if not image_path.exists(): fail(slug, f"image file missing: {image_path}")
        else:
            with Image.open(image_path) as image:
                if image.size != (1600, 900): fail(slug, f"image dimensions are {image.size}, expected 1600x900")
        hero = soup.select_one(".article-hero img, .article-figure img")
        if not hero: fail(slug, "hero image missing")
        else:
            if hero.get("src") != urlparse(og_image).path: fail(slug, "hero image path does not match social image")
            if hero.get("alt") != card.get("imageAlt"): fail(slug, "hero alt differs from blog.ts")
            if not hero.get("width") or not hero.get("height"): fail(slug, "hero image lacks dimensions")
        lede = soup.select_one(".article-hero .lede")
        badge = soup.select_one(".article-hero .badge")
        byline = soup.select_one(".article-byline")
        if h1 != card.get("title"): fail(slug, "H1 differs from homepage card title")
        if not lede or lede.get_text(" ", strip=True) != card.get("excerpt"): fail(slug, "lede differs from homepage excerpt")
        if not badge or badge.get_text(" ", strip=True) != card.get("category"): fail(slug, "category badge differs from homepage category")
        if not byline or card.get("readTime") not in byline.get_text(" ", strip=True): fail(slug, "read time differs from homepage card")
        if not byline or not byline.select_one('a[href="/about-eric-nwankwo/"]'): fail(slug, "byline does not link to author page")
        visible_crumbs = soup.select_one('nav.breadcrumb[aria-label="Breadcrumb"]')
        if not visible_crumbs or not visible_crumbs.select_one('[aria-current="page"]'): fail(slug, "visible breadcrumb lacks a current-page item")
        elif visible_crumbs.select_one('[aria-current="page"]').get_text(" ", strip=True) != h1: fail(slug, "visible breadcrumb final item differs from H1")
        table_labels = [str(node.get("aria-label", "")) for node in soup.select('.article-table-wrap[role="region"]')]
        if any(not label for label in table_labels) or len(table_labels) != len(set(table_labels)): fail(slug, "scrollable table labels are missing or duplicated")

        ld_scripts = []
        for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
            try:
                payload = json.loads(script.string or "")
                ld_scripts.extend(payload.get("@graph", [payload]))
            except json.JSONDecodeError as exc: fail(slug, f"invalid JSON-LD: {exc}")
        article = next((x for x in ld_scripts if x.get("@type") == "BlogPosting"), None)
        breadcrumb = next((x for x in ld_scripts if x.get("@type") == "BreadcrumbList"), None)
        faq = next((x for x in ld_scripts if x.get("@type") == "FAQPage"), None)
        if not article: fail(slug, "BlogPosting schema missing")
        else:
            checks = {
                "headline": h1,
                "description": description,
                "url": canonical,
                "mainEntityOfPage": canonical,
                "articleSection": card.get("category"),
                "datePublished": card.get("publishedAt"),
                "dateModified": card.get("updatedAt"),
            }
            for key, expected in checks.items():
                if article.get(key) != expected: fail(slug, f"BlogPosting {key} differs ({article.get(key)!r} != {expected!r})")
            article_image = article.get("image")
            if article_image not in (og_image, [og_image]): fail(slug, "BlogPosting image differs from social image")
            author = article.get("author", {})
            if author.get("url") != f"{BASE}/about-eric-nwankwo/" and author.get("@id") != f"{BASE}/about-eric-nwankwo/#eric-nwankwo":
                fail(slug, "BlogPosting author URL is wrong")
        if not breadcrumb: fail(slug, "BreadcrumbList schema missing")
        else:
            items = breadcrumb.get("itemListElement", [])
            if [x.get("position") for x in items] != list(range(1, len(items) + 1)): fail(slug, "breadcrumb positions are invalid")
            if not items or items[-1].get("item") != canonical: fail(slug, "breadcrumb final item is not canonical")
        visible = visible_faqs(soup)
        if visible:
            if not faq: fail(slug, "visible FAQs exist without FAQPage schema")
            else:
                structured = [(x.get("name"), x.get("acceptedAnswer", {}).get("text")) for x in faq.get("mainEntity", [])]
                if structured != visible: fail(slug, "FAQ schema does not match visible FAQs")
        elif faq:
            fail(slug, "FAQPage schema exists without visible FAQs")

        for key in ("publishedAt", "updatedAt"):
            value = card.get(key, "")
            if value > today: fail(slug, f"{key} {value} is future-dated")
        if "\u2014" in html: fail(slug, "contains an em dash")
        if 'name="keywords"' in html: fail(slug, "contains obsolete meta keywords")
        if "images.unsplash.com" in html: fail(slug, "contains an external stock-image dependency")
        if "/#resources" in html: fail(slug, "contains obsolete /#resources link")
        if not meta(soup, name="robots").startswith("index,follow"): fail(slug, "robots metadata is not index,follow")
        for link in soup.find_all("a", href=True):
            href = str(link["href"])
            if href.startswith("/"): all_internal_links.add(href)

    sitemap = BeautifulSoup((ROOT / "public" / "sitemap.xml").read_text(encoding="utf-8"), "xml")
    sitemap_urls = {x.get_text(strip=True) for x in sitemap.find_all("loc")}
    expected_urls = {f"{BASE}/blog/{slug}" for slug in EXPECTED}
    missing = expected_urls - sitemap_urls
    if missing: fail("sitemap", f"missing article URLs: {sorted(missing)}")
    if len(sitemap_urls) != 21: fail("sitemap", f"contains {len(sitemap_urls)} URLs, expected 21")

    htaccess = (ROOT / "public" / ".htaccess").read_text(encoding="utf-8")
    for old in ("how-to-start-an-ai-side-hustle-from-scratch-in-2026", "agentic-ai-and-automation-how-to-scale-your-business-career-work-and-life"):
        if old not in htaccess: fail("redirects", f"missing redirect for {old}")

    if ERRORS:
        print("BLOG VALIDATION FAILED")
        for issue in ERRORS: print(f"- {issue}")
        return 1
    print(f"BLOG VALIDATION PASSED: {len(EXPECTED)} articles, 8 social images, {len(sitemap_urls)} sitemap URLs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
